apiVersion: 1
policies:
  - orgId: 1
    receiver: slack-veltrix
    group_by: [alertname, severity]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: email-oncall
        matchers: ['severity = major']
        group_by: [alertname]
        mute_time_intervals: [maintenance-window]
      - receiver: slack-veltrix
        matchers: ['severity = minor']
